[package]
name = "t3tropolis"
version = "0.1.0"
authors = ["Steve Bradley <stevebradley@gmail.com>"]

[dependencies]
nalgebra = "0.8.*"
glfw = "0.2.*"
rand = "0.3"
num = "0.1.32"
rustc-serialize = "0.3"
bincode = "*"
gl = "0.5.*"

[dependencies.kiss3d]
git = "https://github.com/sebcrozet/kiss3d"

